# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: sudo npm install -g firebase-tools
        
      - name: Use Project
        run: firebase use --add goemaat-multiple-apps --token ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Firebase Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
